<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "ecom_product_tools"
 *
 * Auto generated by Extension Builder 2015-02-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[ 'ecom_product_tools' ] = [
	'title' => 'ecom Product Tools',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Sebastian Iffland',
	'author_email' => 'Sebastian.Iffland@ecom-ex.com',
	'author_company' => 'ecom instruments GmbH',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => 0,
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.3.5',
	'constraints' => [
		'depends' => [
			'typo3' => '6.2',
			'php' => '5.4.0-5.6.99',
			'ecom_toolbox' => '',
			't3ecom' => ''
		],
		'conflicts' => [],
		'suggests' => []
	]
];
